version: '2'
services:
  radarr:
    image: ${HTPC_PLATFORM}/radarr
    restart: ${HTPC_RESTART_POLICY}
    ports:
     - "7878:7878"
    volumes:
     - ${HTPC_CONFIG_HOME}/radarr:/config
     - ${HTPC_DOWNLOAD_HOME}/downloads:/downloads
     - ${HTPC_MEDIA_HOME}/media/videos/movies:/movies
    extra_hosts:
     - "kodi:${HTPC_KODI_HOST}"     
    environment:
     - TZ=${HTPC_TIMEZONE}
     - PGID=${HTPC_GROUP_ID}
     - PUID=${HTPC_USER_ID}