version: '2'
services:
  sickrage:
    image: lsioarmhf/sickrage
    restart: ${HTPC_RESTART_POLICY}
    depends_on:
      - transmission
    ports:
     - "8081:8081"
    volumes:
     - ${HTPC_CONFIG_HOME}/sickrage:/config
     - ${HTPC_MEDIA_HOME}/downloads:/downloads
     - ${HTPC_MEDIA_HOME}/media/videos/tvshows:/tv
    extra_hosts:
     - "kodi:${KODI_HOST}"     
    environment:
     - TZ=${HTPC_TIMEZONE}
     - PGID=${HTPC_GROUP_ID}
     - PUID=${HTPC_USER_ID}
