version: '2'
services:
  sickrage:
    image: ${HTPC_PLATFORM}/sickrage
    restart: ${HTPC_RESTART_POLICY}
    ports:
     - "8081:8081"
    volumes:
     - ${HTPC_CONFIG_HOME}/sickrage:/config
     - ${HTPC_DOWNLOAD_HOME}/downloads:/downloads
     - ${HTPC_MEDIA_HOME}/media/videos/tvshows:/tv
    extra_hosts:
     - "kodi:${HTPC_KODI_HOST}"     
    environment:
     - TZ=${HTPC_TIMEZONE}
     - PGID=${HTPC_GROUP_ID}
     - PUID=${HTPC_USER_ID}
