#!/usr/bin/with-contenv bash

# install app
[[ ! -d /app/sickrage/.git ]] && \
	git clone https://donna.devices.wvvw.me/sickrage/sickrage.git /app/sickrage

# permissions
chown -R abc:abc \
	/app \
	/config
